# clamd.conf for RustGuard
# Se utiliza para levantar el demonio en segundo plano (clamd.exe)

# Configuración de Conexión TCP
TCPSocket 3310
TCPAddr 127.0.0.1

# Directorio de Base de Datos
DatabaseDirectory "./clamav_db"

# Límites de Escaneo (Balanceados para evitar consumo extremo de memoria)
MaxDirectoryRecursion 20
MaxRecursion 15
MaxFiles 10000
MaxFileSize 500M
MaxScanSize 500M

# Opciones de Archivos Comprimidos
ScanArchive yes
MaxEmbeddedPE 40M
MaxHTMLNormalize 10M
MaxHTMLNoTags 2M
MaxScriptNormalize 5M

# Opciones Generales
ScanPE yes
ScanELF yes
ScanOLE2 yes
ScanPDF yes
ScanSWF yes
ScanXMLDOCS yes
ScanHWP3 yes
