sonar.projectKey=RustGuard-VSCode
sonar.projectName=RustGuard Antivirus Scanner
sonar.projectVersion=1.0.3

# Archivos a analizar
sonar.sources=src
sonar.language=ts

# Reporte de cobertura (LCOV generado por Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Archivos a excluir
sonar.exclusions=**/node_modules/**,**/out/**,**/tests/**
